name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "dev-r2-anycontext"

[[d1_databases]]
binding = "DATABASE"
database_name = "dev-d1-anycontext"
database_id = "fc562605-157a-4f60-b439-2a24ffed5b4c"

[[kv_namespaces]]
binding = "CANVAS_SNAPS"
id = "c6446f7190dd4afebe1c318df3400518"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "prod-d1-supermemory"
database_id = "f527a727-c472-41d4-8eaf-3d7ba0f2f395"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "dev-d1-anycontext"
database_id = "fc562605-157a-4f60-b439-2a24ffed5b4c"