name: Build and Deploy Changes

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'apps/extension/**'
      - 'apps/cf-ai-backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'apps/extension/**'
      - 'apps/cf-ai-backend/**'

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/buildextension

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: bun i
        shell: bash

      - name: Build app
        run: bun run pages:build
        working-directory: apps/web
        shell: bash
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          BACKEND_SECURITY_KEY: ${{ secrets.BACKEND_SECURITY_KEY }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: apps/web/.vercel/output/static
          branch: main

  deploy-cf-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          script: wrangler publish
          working-directory: apps/cf-ai-backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SECURITY_KEY: ${{ secrets.BACKEND_SECURITY_KEY }}
